Dispatch 1948
apache/qpid-dispatch pull request #1015
Opened 2021-02-02 22:05 UTC by kgiusti

2021-02-02 22:34 UTC, ganeshmurthy approved these changes

2021-02-03 07:32 UTC, jiridanek requested changes
Looks like it fixed the ubsan warnings, except this one kind

```
1: ../src/parse.c:509:74: runtime error: left shift of 128 by 24 places cannot be represented in type 'int'
```

2021-02-03 07:32 UTC, jiridanek commented on src/alloc_pool.c
> +    const uint32_t pb = PATTERN_BACK;
```
/home/travis/build/apache/qpid-dispatch/src/alloc_pool.c:440:20: error: unused variable 'pb' [-Werror,-Wunused-variable]

    const uint32_t pb = PATTERN_BACK;
```

2021-02-03 07:32 UTC, jiridanek commented on src/alloc_pool.c
> +    const uint32_t pb = PATTERN_BACK;
(That's because the next line is an assert, so it may not be always compiled in...)

2021-02-03 07:32 UTC, jiridanek commented on src/alloc_pool.c
> +    assert (memcmp(p + desc->total_size, &pb, sizeof(pb)) == 0);
I imagine Coverity will scream about this. Memcpy has side-efects and it is being used in an assert.

2021-02-03 07:33 UTC, jiridanek commented on src/alloc_pool.c
> +    assert (memcmp(p + desc->total_size, &pb, sizeof(pb)) == 0);
Uh, memcmp, never mind.

2021-02-04 14:29 UTC, jiridanek approved these changes
lgtm.

tests failed on GHA with known issue

```
 69: qdrouterd: ../src/router_core/transfer.c:225: qdr_link_process_deliveries: Assertion `(link->undelivered).head' failed.
```

https://github.com/apache/qpid-dispatch/pull/1015/checks?check_run_id=1826269317#step:9:2078

And on Travis with some (old) TSAN warnings

2021-02-12 21:23 UTC, closed without merging